.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions. It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are __not_case_sensitive__, so only one target definition
   is needed for scikit-umfpack, Scikit-Umfpack, Scikit-UMFPACK, etc...

.. _scikit-umfpack: https://pypi.python.org/pypi/scikit-umfpack

.. _pypi: https://pypi.python.org/pypi
.. _testpypi: https://testpypi.python.org/pypi
.. _twine: https://pypi.python.org/pypi/twine

.. _venv: https://docs.python.org/3/library/venv.html
